//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoDivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoDivision()
        {
            this.AlumnoInasistencia = new HashSet<AlumnoInasistencia>();
            this.AlumnoInasistenciaSuscripcion = new HashSet<AlumnoInasistenciaSuscripcion>();
            this.AlumnoNota = new HashSet<AlumnoNota>();
        }
    
        public int idAlumnoDivision { get; set; }
        public int idAlumno { get; set; }
        public int idDivision { get; set; }
        public int anioLectivo { get; set; }
        public Nullable<int> idEstadoAlumno { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idMotivoBaja { get; set; }
        public Nullable<int> idTipoNovedad { get; set; }
        public Nullable<int> idAlumnoDivisionBaja { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Division Division { get; set; }
        public virtual RefTipoNovedad RefTipoNovedad { get; set; }
        public virtual RefTipoNovedad RefTipoNovedad1 { get; set; }
        public virtual RefTipoNovedad RefTipoNovedad2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoInasistencia> AlumnoInasistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoInasistenciaSuscripcion> AlumnoInasistenciaSuscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoNota> AlumnoNota { get; set; }
    }
}
