//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoFamilia
    {
        public int idAlumnoFamilia { get; set; }
        public int idAlumno { get; set; }
        public int idFamilia { get; set; }
        public int idParentesco { get; set; }
        public Nullable<bool> esTutor { get; set; }
        public Nullable<bool> cuidaAlumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Familia Familia { get; set; }
        public virtual RefParentesco RefParentesco { get; set; }
    }
}
