//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoNota
    {
        public int idAlumnoNota { get; set; }
        public int idAlumno { get; set; }
        public int idAlumnoDivision { get; set; }
        public int anioLectivo { get; set; }
        public int idAsignatura { get; set; }
        public int idPeriodoEscolar { get; set; }
        public int nota { get; set; }
        public string observacion { get; set; }
    
        public virtual AlumnoDivision AlumnoDivision { get; set; }
        public virtual RefAsignatura RefAsignatura { get; set; }
    }
}
