//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.AlumnoAntropometria = new HashSet<AlumnoAntropometria>();
            this.AlumnoAsignatura = new HashSet<AlumnoAsignatura>();
            this.AlumnoDivision = new HashSet<AlumnoDivision>();
            this.AlumnoFamilia = new HashSet<AlumnoFamilia>();
        }
    
        public int idAlumno { get; set; }
        public int idTipoDocumento { get; set; }
        public Nullable<int> nroDocumento { get; set; }
        public Nullable<int> preCuil { get; set; }
        public Nullable<int> sufCuil { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public int idSexo { get; set; }
        public Nullable<int> idEstadoCivil { get; set; }
        public Nullable<System.DateTime> fechaNac { get; set; }
        public Nullable<int> idLocalidadLugarNac { get; set; }
        public Nullable<int> idPaisNacionalidad { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaFallecimiento { get; set; }
        public string calle { get; set; }
        public Nullable<int> numero { get; set; }
        public string piso { get; set; }
        public string dpto { get; set; }
        public string lote { get; set; }
        public string manzana { get; set; }
        public string barrio { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<int> personasACargo { get; set; }
        public Nullable<bool> trabaja { get; set; }
        public Nullable<bool> aborigen { get; set; }
        public Nullable<bool> lengua_indigena { get; set; }
        public Nullable<bool> estaActivo { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual Localidad Localidad1 { get; set; }
        public virtual RefEstadoCivil RefEstadoCivil { get; set; }
        public virtual RefPaisNacionalidad RefPaisNacionalidad { get; set; }
        public virtual RefSexo RefSexo { get; set; }
        public virtual RefTipoDocumento RefTipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoAntropometria> AlumnoAntropometria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoAsignatura> AlumnoAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoDivision> AlumnoDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoFamilia> AlumnoFamilia { get; set; }
    }
}
