//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoAntropometria
    {
        public int idAlumnoAntropometria { get; set; }
        public int IdAlumno { get; set; }
        public int nro_medicion { get; set; }
        public Nullable<int> talla { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<System.DateTime> fecha_medicion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
