//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoAsignatura
    {
        public int idAlumnoAsignatura { get; set; }
        public int idAlumno { get; set; }
        public int idAsignatura { get; set; }
        public int idDivision { get; set; }
        public int idTipoAsignaturaPrevia { get; set; }
        public bool equivalencia { get; set; }
        public bool aprobada { get; set; }
        public int anioLectivo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Division Division { get; set; }
        public virtual RefAsignatura RefAsignatura { get; set; }
        public virtual RefTipoAsignaturaPrevia RefTipoAsignaturaPrevia { get; set; }
    }
}
