//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoInasistenciaSuscripcion
    {
        public int idAlumnoInasistenciaSuscripcion { get; set; }
        public int idFamilia { get; set; }
        public int idAlumnoDivision { get; set; }
        public bool estaActivo { get; set; }
    
        public virtual AlumnoDivision AlumnoDivision { get; set; }
        public virtual Familia Familia { get; set; }
    }
}
