//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoInasistencia
    {
        public int idAlumnoInasistencia { get; set; }
        public int idAlumnoDivision { get; set; }
        public int idTipoInasistencia { get; set; }
        public System.DateTime fecha { get; set; }
        public bool justificada { get; set; }
        public string observacion { get; set; }
    
        public virtual AlumnoDivision AlumnoDivision { get; set; }
        public virtual RefTipoInasistencia RefTipoInasistencia { get; set; }
    }
}
