//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircuitoSolicitud
    {
        public int idSolicitud { get; set; }
        public int nroOrden { get; set; }
        public int idEstadoSolicitud { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> nuevoNroSol { get; set; }
    }
}
