//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionACrear
    {
        public int idDivisionACrear { get; set; }
        public int idPlanUnidad { get; set; }
        public int idOrganizacionTurno { get; set; }
        public string curso { get; set; }
        public string division { get; set; }
        public bool estaActivo { get; set; }
        public bool esGrupo { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual OrganizacionTurno OrganizacionTurno { get; set; }
        public virtual PlanUnidad PlanUnidad { get; set; }
    }
}
