//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edificio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edificio()
        {
            this.EdificioOrganizacion = new HashSet<EdificioOrganizacion>();
        }
    
        public int idEdificio { get; set; }
        public string edificio1 { get; set; }
        public string cui { get; set; }
        public int idTipoEdificio { get; set; }
        public string domicilio { get; set; }
        public int idLocalidad { get; set; }
        public Nullable<System.DateTime> fechaConstruccion { get; set; }
        public Nullable<int> superficie { get; set; }
        public Nullable<int> superficieLibre { get; set; }
        public Nullable<int> superficieAulas { get; set; }
        public Nullable<int> superficieCubierta { get; set; }
        public int idEstadoEdificio { get; set; }
        public int idTipoTenencia { get; set; }
        public bool estaActivo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual RefEstadoEdificio RefEstadoEdificio { get; set; }
        public virtual RefTipoEdificio RefTipoEdificio { get; set; }
        public virtual RefTipoTenencia RefTipoTenencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdificioOrganizacion> EdificioOrganizacion { get; set; }
    }
}
