//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspacioCurricular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EspacioCurricular()
        {
            this.EspacioAsignatura = new HashSet<EspacioAsignatura>();
            this.PlanEspacio = new HashSet<PlanEspacio>();
        }
    
        public int idEspacioCurricular { get; set; }
        public Nullable<int> idTipoEspacioCurricular { get; set; }
        public string espacioCurricular1 { get; set; }
        public bool estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspacioAsignatura> EspacioAsignatura { get; set; }
        public virtual RefTipoEspacioCurricular RefTipoEspacioCurricular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanEspacio> PlanEspacio { get; set; }
    }
}
