//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.AlumnoFamilia = new HashSet<AlumnoFamilia>();
            this.AlumnoInasistenciaSuscripcion = new HashSet<AlumnoInasistenciaSuscripcion>();
        }
    
        public int idFamilia { get; set; }
        public int idTipoDocumento { get; set; }
        public Nullable<int> nroDocumento { get; set; }
        public Nullable<int> preCuil { get; set; }
        public Nullable<int> sufCuil { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public int idSexo { get; set; }
        public Nullable<int> idEstadoCivil { get; set; }
        public Nullable<System.DateTime> fechaNac { get; set; }
        public Nullable<int> idPaisNacionalidad { get; set; }
        public Nullable<int> idNivelEducativo { get; set; }
        public string telefono { get; set; }
        public Nullable<int> celular { get; set; }
        public Nullable<bool> vive { get; set; }
        public Nullable<bool> trabaja { get; set; }
        public Nullable<bool> jubilado { get; set; }
        public Nullable<bool> pensionado { get; set; }
        public bool estaActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoFamilia> AlumnoFamilia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoInasistenciaSuscripcion> AlumnoInasistenciaSuscripcion { get; set; }
        public virtual RefEstadoCivil RefEstadoCivil { get; set; }
        public virtual RefNivelEducativo RefNivelEducativo { get; set; }
        public virtual RefPaisNacionalidad RefPaisNacionalidad { get; set; }
        public virtual RefSexo RefSexo { get; set; }
        public virtual RefTipoDocumento RefTipoDocumento { get; set; }
    }
}
