//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoDivision
    {
        public int idGrupoDivision { get; set; }
        public int idGrupo { get; set; }
        public int idDivision { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
