//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licencia()
        {
            this.LicenciaPorSituacionDeRevista = new HashSet<LicenciaPorSituacionDeRevista>();
            this.SubServicio = new HashSet<SubServicio>();
        }
    
        public int idLicencia { get; set; }
        public string licencia1 { get; set; }
        public string numeroArticulo { get; set; }
        public int idInstrumentoLegal { get; set; }
        public int idCategoriaLicencia { get; set; }
        public int idTipoGoceHaber { get; set; }
        public Nullable<int> duracionMinima { get; set; }
        public Nullable<int> idUTDuracionMinima { get; set; }
        public Nullable<int> idUTCDuracionMinima { get; set; }
        public Nullable<int> duracionMaxima { get; set; }
        public Nullable<int> idUTDuracionMaxima { get; set; }
        public Nullable<int> idUTCDuracionMaxima { get; set; }
        public Nullable<int> antiguedadMinimaAnios { get; set; }
        public Nullable<int> antiguedadMinimaMeses { get; set; }
        public bool pierdePresentismo { get; set; }
        public bool cuentaIncompatibilidad { get; set; }
        public bool requiereFechaBajaObligatoria { get; set; }
        public bool estaActivo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual InstrumentoLegal InstrumentoLegal { get; set; }
        public virtual RefCategoriaLicencia RefCategoriaLicencia { get; set; }
        public virtual RefTipoGoceHaber RefTipoGoceHaber { get; set; }
        public virtual RefUnidadTemporal RefUnidadTemporal { get; set; }
        public virtual RefUnidadTemporal RefUnidadTemporal1 { get; set; }
        public virtual RefUnidadTemporalContexto RefUnidadTemporalContexto { get; set; }
        public virtual RefUnidadTemporalContexto RefUnidadTemporalContexto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenciaPorSituacionDeRevista> LicenciaPorSituacionDeRevista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubServicio> SubServicio { get; set; }
    }
}
