//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenciaPorSituacionDeRevista
    {
        public int idLicencia { get; set; }
        public int idSituacionRevista { get; set; }
        public bool estaActivo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual Licencia Licencia { get; set; }
        public virtual RefSituacionRevista RefSituacionRevista { get; set; }
    }
}
