//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPlaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuPlaza()
        {
            this.MenuPlaza1 = new HashSet<MenuPlaza>();
        }
    
        public int idMenu { get; set; }
        public int idMenuPadre { get; set; }
        public Nullable<bool> menuPersonalizado { get; set; }
        public Nullable<int> menuOrden { get; set; }
        public Nullable<bool> menuSeleccionable { get; set; }
        public string menuUrl { get; set; }
        public string menuTabla { get; set; }
        public string menuImagen { get; set; }
        public string menuNombre { get; set; }
        public Nullable<int> idDetalleTabla { get; set; }
        public Nullable<bool> estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual DetalleTabla DetalleTabla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPlaza> MenuPlaza1 { get; set; }
        public virtual MenuPlaza MenuPlaza2 { get; set; }
    }
}
