//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRHH_V2Entities : DbContext
    {
        public RRHH_V2Entities()
            : base("name=RRHH_V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agente> Agente { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoAntropometria> AlumnoAntropometria { get; set; }
        public virtual DbSet<AlumnoAsignatura> AlumnoAsignatura { get; set; }
        public virtual DbSet<AlumnoDivision> AlumnoDivision { get; set; }
        public virtual DbSet<AlumnoDivisonHistorial> AlumnoDivisonHistorial { get; set; }
        public virtual DbSet<AlumnoFamilia> AlumnoFamilia { get; set; }
        public virtual DbSet<AlumnoInasistencia> AlumnoInasistencia { get; set; }
        public virtual DbSet<AlumnoInasistenciaSuscripcion> AlumnoInasistenciaSuscripcion { get; set; }
        public virtual DbSet<AlumnoNota> AlumnoNota { get; set; }
        public virtual DbSet<AlumnosUsuarios> AlumnosUsuarios { get; set; }
        public virtual DbSet<CargoFuncional> CargoFuncional { get; set; }
        public virtual DbSet<CargoSalarial> CargoSalarial { get; set; }
        public virtual DbSet<CargoSalarialFuncional> CargoSalarialFuncional { get; set; }
        public virtual DbSet<CategoriaPresupuesto> CategoriaPresupuesto { get; set; }
        public virtual DbSet<CircuitoSolicitud> CircuitoSolicitud { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetalleTabla> DetalleTabla { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<DivisionACrear> DivisionACrear { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<EdificioOrganizacion> EdificioOrganizacion { get; set; }
        public virtual DbSet<EspacioAsignatura> EspacioAsignatura { get; set; }
        public virtual DbSet<EspacioCurricular> EspacioCurricular { get; set; }
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<GrupoDivision> GrupoDivision { get; set; }
        public virtual DbSet<InstrumentoLegal> InstrumentoLegal { get; set; }
        public virtual DbSet<Licencia> Licencia { get; set; }
        public virtual DbSet<LicenciaPorSituacionDeRevista> LicenciaPorSituacionDeRevista { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<MenuPlaza> MenuPlaza { get; set; }
        public virtual DbSet<MovimientosPresupuesto> MovimientosPresupuesto { get; set; }
        public virtual DbSet<Organizacion> Organizacion { get; set; }
        public virtual DbSet<OrganizacionTurno> OrganizacionTurno { get; set; }
        public virtual DbSet<PaquetePlaza> PaquetePlaza { get; set; }
        public virtual DbSet<PaquetePlazaHistorica> PaquetePlazaHistorica { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PlanEspacio> PlanEspacio { get; set; }
        public virtual DbSet<PlanEstudio> PlanEstudio { get; set; }
        public virtual DbSet<PlanUnidad> PlanUnidad { get; set; }
        public virtual DbSet<Plaza> Plaza { get; set; }
        public virtual DbSet<PlazaHistorica> PlazaHistorica { get; set; }
        public virtual DbSet<Presupuesto> Presupuesto { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<RefAdicional> RefAdicional { get; set; }
        public virtual DbSet<RefAfectacion> RefAfectacion { get; set; }
        public virtual DbSet<RefAmbito> RefAmbito { get; set; }
        public virtual DbSet<RefAsignatura> RefAsignatura { get; set; }
        public virtual DbSet<RefCalendarioFeriado> RefCalendarioFeriado { get; set; }
        public virtual DbSet<RefCargoTipo> RefCargoTipo { get; set; }
        public virtual DbSet<RefCategoriaLicencia> RefCategoriaLicencia { get; set; }
        public virtual DbSet<RefCategoriaOrganizacion> RefCategoriaOrganizacion { get; set; }
        public virtual DbSet<RefDiaDescansoAnual> RefDiaDescansoAnual { get; set; }
        public virtual DbSet<RefEscalafon> RefEscalafon { get; set; }
        public virtual DbSet<RefEspecialidad> RefEspecialidad { get; set; }
        public virtual DbSet<RefEstado> RefEstado { get; set; }
        public virtual DbSet<RefEstadoCivil> RefEstadoCivil { get; set; }
        public virtual DbSet<RefEstadoEdificio> RefEstadoEdificio { get; set; }
        public virtual DbSet<RefEstadoSolicitud> RefEstadoSolicitud { get; set; }
        public virtual DbSet<RefFinalidad> RefFinalidad { get; set; }
        public virtual DbSet<RefFinanciamiento> RefFinanciamiento { get; set; }
        public virtual DbSet<RefFuncion> RefFuncion { get; set; }
        public virtual DbSet<RefJornada> RefJornada { get; set; }
        public virtual DbSet<RefMotivoAlta> RefMotivoAlta { get; set; }
        public virtual DbSet<RefMotivoBaja> RefMotivoBaja { get; set; }
        public virtual DbSet<RefMotivoCreacion> RefMotivoCreacion { get; set; }
        public virtual DbSet<RefMotivoMovimientoPres> RefMotivoMovimientoPres { get; set; }
        public virtual DbSet<RefMovimiento> RefMovimiento { get; set; }
        public virtual DbSet<RefNivelEducativo> RefNivelEducativo { get; set; }
        public virtual DbSet<RefPaisNacionalidad> RefPaisNacionalidad { get; set; }
        public virtual DbSet<RefParentesco> RefParentesco { get; set; }
        public virtual DbSet<RefPeriodoEscolar> RefPeriodoEscolar { get; set; }
        public virtual DbSet<RefRegimenLaboral> RefRegimenLaboral { get; set; }
        public virtual DbSet<RefRegimenSalarial> RefRegimenSalarial { get; set; }
        public virtual DbSet<RefRegion> RefRegion { get; set; }
        public virtual DbSet<RefSexo> RefSexo { get; set; }
        public virtual DbSet<RefSistemaEducativo> RefSistemaEducativo { get; set; }
        public virtual DbSet<RefSituacionExtraordinaria> RefSituacionExtraordinaria { get; set; }
        public virtual DbSet<RefSituacionLaboral> RefSituacionLaboral { get; set; }
        public virtual DbSet<RefSituacionRevista> RefSituacionRevista { get; set; }
        public virtual DbSet<RefTipoAsignaturaPrevia> RefTipoAsignaturaPrevia { get; set; }
        public virtual DbSet<RefTipoDocumento> RefTipoDocumento { get; set; }
        public virtual DbSet<RefTipoEdificio> RefTipoEdificio { get; set; }
        public virtual DbSet<RefTipoEducacion> RefTipoEducacion { get; set; }
        public virtual DbSet<RefTipoEspacioCurricular> RefTipoEspacioCurricular { get; set; }
        public virtual DbSet<RefTipoFuncion> RefTipoFuncion { get; set; }
        public virtual DbSet<RefTipoGoceHaber> RefTipoGoceHaber { get; set; }
        public virtual DbSet<RefTipoInasistencia> RefTipoInasistencia { get; set; }
        public virtual DbSet<RefTipoInstrumentoLegal> RefTipoInstrumentoLegal { get; set; }
        public virtual DbSet<RefTipoNovedad> RefTipoNovedad { get; set; }
        public virtual DbSet<RefTipoOrganizacion> RefTipoOrganizacion { get; set; }
        public virtual DbSet<RefTipoPaquetePlaza> RefTipoPaquetePlaza { get; set; }
        public virtual DbSet<RefTipoServicio> RefTipoServicio { get; set; }
        public virtual DbSet<RefTipoSolicitud> RefTipoSolicitud { get; set; }
        public virtual DbSet<RefTipoTenencia> RefTipoTenencia { get; set; }
        public virtual DbSet<RefTurno> RefTurno { get; set; }
        public virtual DbSet<RefUdeO> RefUdeO { get; set; }
        public virtual DbSet<RefUnidadTemporal> RefUnidadTemporal { get; set; }
        public virtual DbSet<RefUnidadTemporalContexto> RefUnidadTemporalContexto { get; set; }
        public virtual DbSet<RefZona> RefZona { get; set; }
        public virtual DbSet<ReqSolicitudPrimaria> ReqSolicitudPrimaria { get; set; }
        public virtual DbSet<ReqSolicitudSecundaria> ReqSolicitudSecundaria { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<SubServicio> SubServicio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
