//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosPresupuesto
    {
        public int idMovimiento { get; set; }
        public int idPresupuesto { get; set; }
        public System.DateTime fecha { get; set; }
        public int idMotivoMovimientoPres { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> idInstrumentoLegal { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public int cantidad { get; set; }
        public bool estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual RefMotivoMovimientoPres RefMotivoMovimientoPres { get; set; }
    }
}
