//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetePlazaHistorica
    {
        public int idPaquetePlazaHistorica { get; set; }
        public int idPaquete { get; set; }
        public int idPlazaCabecera { get; set; }
        public int idTipoPaquetePlaza { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int idMotivoBaja { get; set; }
    
        public virtual RefMotivoBaja RefMotivoBaja { get; set; }
    }
}
