//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int idPartida { get; set; }
        public int idFinalidad { get; set; }
        public int idFuncion { get; set; }
        public string idEscalafon { get; set; }
        public bool estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual RefEscalafon RefEscalafon { get; set; }
        public virtual RefFinalidad RefFinalidad { get; set; }
        public virtual RefFuncion RefFuncion { get; set; }
    }
}
