//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEspacio
    {
        public int idPlanEspacio { get; set; }
        public int idPlanEstudio { get; set; }
        public int idEspacioCurricular { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> cargaHoraria { get; set; }
        public Nullable<bool> estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual EspacioCurricular EspacioCurricular { get; set; }
        public virtual PlanEstudio PlanEstudio { get; set; }
    }
}
