//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEstudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanEstudio()
        {
            this.PlanEspacio = new HashSet<PlanEspacio>();
            this.PlanUnidad = new HashSet<PlanUnidad>();
        }
    
        public int idPlanEstudio { get; set; }
        public int idEspecialidad { get; set; }
        public Nullable<int> idInstrumentoLegal { get; set; }
        public string planEstudio1 { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public Nullable<int> duracion { get; set; }
        public bool estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual InstrumentoLegal InstrumentoLegal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanEspacio> PlanEspacio { get; set; }
        public virtual RefEspecialidad RefEspecialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanUnidad> PlanUnidad { get; set; }
    }
}
