//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuesto()
        {
            this.Plaza = new HashSet<Plaza>();
        }
    
        public int idPresupuesto { get; set; }
        public int idCategoriaPresupuesto { get; set; }
        public int idAdicional { get; set; }
        public int cantPresupuestada { get; set; }
        public Nullable<int> cantOcupada { get; set; }
        public string observacion { get; set; }
        public int ejercicio { get; set; }
        public bool estaActivo { get; set; }
        public bool esFormal { get; set; }
        public Nullable<int> cantTitulares { get; set; }
        public Nullable<int> cantInterinos { get; set; }
        public int idInstrumentoLegal { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
    
        public virtual CategoriaPresupuesto CategoriaPresupuesto { get; set; }
        public virtual InstrumentoLegal InstrumentoLegal { get; set; }
        public virtual RefAdicional RefAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plaza> Plaza { get; set; }
    }
}
