//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqSolicitudSecundaria
    {
        public int idSolicitud { get; set; }
        public int idRequerimiento { get; set; }
        public int cantidad { get; set; }
        public int idCategoriaPresupuesto { get; set; }
        public int idCargoFuncional { get; set; }
        public Nullable<int> idPlanUnidad { get; set; }
        public Nullable<int> idDivision { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public Nullable<int> idEspacioAsignatura { get; set; }
        public string caracter { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public string observacion { get; set; }
        public int idEstadoRequerimiento { get; set; }
        public string obsEstado { get; set; }
        public bool esCargo { get; set; }
        public string partidaTEducacion { get; set; }
        public Nullable<int> cupof { get; set; }
        public Nullable<int> pCupof { get; set; }
        public Nullable<bool> admiteSuplente { get; set; }
        public Nullable<bool> cobraIncentivo { get; set; }
        public Nullable<int> idSistemaEducativo { get; set; }
        public Nullable<int> idRegimenLaboral { get; set; }
        public Nullable<int> idFinanciamiento { get; set; }
        public Nullable<int> idRegimenSalarial { get; set; }
    
        public virtual CargoFuncional CargoFuncional { get; set; }
        public virtual CategoriaPresupuesto CategoriaPresupuesto { get; set; }
        public virtual Division Division { get; set; }
        public virtual EspacioAsignatura EspacioAsignatura { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual PlanUnidad PlanUnidad { get; set; }
        public virtual RefEstadoSolicitud RefEstadoSolicitud { get; set; }
        public virtual RefFinanciamiento RefFinanciamiento { get; set; }
        public virtual RefRegimenLaboral RefRegimenLaboral { get; set; }
        public virtual RefRegimenSalarial RefRegimenSalarial { get; set; }
        public virtual RefSistemaEducativo RefSistemaEducativo { get; set; }
        public virtual ReqSolicitudSecundaria ReqSolicitudSecundaria1 { get; set; }
        public virtual ReqSolicitudSecundaria ReqSolicitudSecundaria2 { get; set; }
    }
}
