//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.SubServicio = new HashSet<SubServicio>();
            this.SubServicio1 = new HashSet<SubServicio>();
        }
    
        public int idServicio { get; set; }
        public int idAgente { get; set; }
        public int idPlaza { get; set; }
        public Nullable<int> idPlazaHistorica { get; set; }
        public int idSituacionRevista { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public Nullable<bool> estaActivo { get; set; }
        public Nullable<int> idTipoServicio { get; set; }
        public Nullable<int> idInstrumentoLegalAlta { get; set; }
        public Nullable<int> idInstrumentoLegalBaja { get; set; }
        public int idMotivoAlta { get; set; }
        public Nullable<int> idMotivoBaja { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual InstrumentoLegal InstrumentoLegal { get; set; }
        public virtual InstrumentoLegal InstrumentoLegal1 { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual PlazaHistorica PlazaHistorica { get; set; }
        public virtual RefMotivoAlta RefMotivoAlta { get; set; }
        public virtual RefMotivoBaja RefMotivoBaja { get; set; }
        public virtual RefSituacionRevista RefSituacionRevista { get; set; }
        public virtual RefTipoServicio RefTipoServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubServicio> SubServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubServicio> SubServicio1 { get; set; }
    }
}
