//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.ReqSolicitudPrimaria = new HashSet<ReqSolicitudPrimaria>();
        }
    
        public int idSolicitud { get; set; }
        public string nroExpediente { get; set; }
        public int idTipoSolicitud { get; set; }
        public int idOrganizacion { get; set; }
        public Nullable<int> matriculaTotal { get; set; }
        public Nullable<int> cantDivisiones { get; set; }
        public int idGrupoNivel { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string fundamentacion { get; set; }
        public string observacion { get; set; }
        public int idEstadoSolicitud { get; set; }
        public string obsEstado { get; set; }
        public string nroResolucion { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaAutorizacion { get; set; }
        public Nullable<System.DateTime> fechaHabilitacion { get; set; }
        public bool estaActivo { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
        public Nullable<int> idUsuarioCreador { get; set; }
    
        public virtual Organizacion Organizacion { get; set; }
        public virtual RefEstadoSolicitud RefEstadoSolicitud { get; set; }
        public virtual RefTipoSolicitud RefTipoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqSolicitudPrimaria> ReqSolicitudPrimaria { get; set; }
    }
}
