//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    
    public partial class spInstrumentoLegalSELbyTexto__Result1
    {
        public int idInstrumentoLegal { get; set; }
        public string instrumentoLegal { get; set; }
        public string tipoInstrumentoLegal { get; set; }
        public string descripcion { get; set; }
        public bool estaActivo { get; set; }
    }
}
