//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIARH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubServicio
    {
        public int idSubServicio { get; set; }
        public int idServicio { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public Nullable<int> idInstrumentoLegalAlta { get; set; }
        public Nullable<int> idInstrumentoLegalBaja { get; set; }
        public int idMotivoAlta { get; set; }
        public Nullable<int> idMotivoBaja { get; set; }
        public int idMovimiento { get; set; }
        public int idSituacionLaboral { get; set; }
        public Nullable<int> idSituacionExtraordinaria { get; set; }
        public Nullable<int> idLicencia { get; set; }
        public Nullable<int> idServicioLigado { get; set; }
        public Nullable<int> idAdicional { get; set; }
        public bool estaActivo { get; set; }
        public bool estaFrenteAlumno { get; set; }
        public Nullable<bool> cobraComplemento { get; set; }
        public Nullable<bool> cobraIncentivo { get; set; }
    
        public virtual InstrumentoLegal InstrumentoLegal { get; set; }
        public virtual InstrumentoLegal InstrumentoLegal1 { get; set; }
        public virtual Licencia Licencia { get; set; }
        public virtual RefAdicional RefAdicional { get; set; }
        public virtual RefMotivoAlta RefMotivoAlta { get; set; }
        public virtual RefMotivoBaja RefMotivoBaja { get; set; }
        public virtual RefMovimiento RefMovimiento { get; set; }
        public virtual RefSituacionExtraordinaria RefSituacionExtraordinaria { get; set; }
        public virtual RefSituacionLaboral RefSituacionLaboral { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Servicio Servicio1 { get; set; }
    }
}
